### ISSUE TITLE
ESBootStrap.sh awk correction

### ISSUE THREAD

**Issue by cruepprich** [oracle-quickstart/oci-elastic#11]
I had to make a change to the bootstrap script. I changed the awk print argument from $4 to $2:

esmasternode1=`host esmasternode1.privad1|awk '{print $2}'`
esmasternode2=`host esmasternode2.privad2|awk '{print $2}'`
esmasternode3=`host esmasternode3.privad3|awk '{print $2}'`
esdatanode1=`host esdatanode1.privad1|awk '{print $2}'`
esdatanode2=`host esdatanode2.privad1|awk '{print $2}'`
esdatanode3=`host esdatanode3.privad2|awk '{print $2}'`
esdatanode4=`host esdatanode4.privad2|awk '{print $2}'`

Other than that, it worked like a charm.

**Comment by lfeldman** [comment]
@cruepprich what was the intention of this change in bootstrap script? With $2 Was it just not working or you have found it better to use $4?

**Comment by lfeldman** [comment]
@cruepprich I have tested the code and it looks like $2 is wrong:

```
Last login: Tue Jan 18 11:38:05 2022 from bastionhost.bastsub.ociesvcn.oraclevcn.com
[opc@esdatanode1 ~]$ esmasternode1=`host esmasternode1.privad1|awk '{print $4}'`
[opc@esdatanode1 ~]$ echo $esmasternode1
192.168.0.21
[opc@esdatanode1 ~]$ esmasternode1=`host esmasternode1.privad1|awk '{print $2}'`
[opc@esdatanode1 ~]$ echo $esmasternode1
has
```

Closing the ticket.
