### ISSUE TITLE
unable to create simple elk on oci

### ISSUE THREAD

**Issue by RupakRath** [oracle-quickstart/oci-elastic#14]
showing error
 can not create client, bad configuration: did not find a proper configuration for private key

**Comment by nugoncal** [comment]
Hi @RupakRath ,
I am unable to reproduce the issue. How does your .tfvars file look like? Please share, with hashed/incomplete values, if you wish. Here's a sample of what I'm using for a successful deployment of the /simple subfolder.

![image](https://user-images.githubusercontent.com/87083656/149778304-b3ae1218-a012-4f64-8d30-ed1c19815a83.png)

**Comment by nugoncal** [comment]
Moving this issue to closed.
