### ISSUE TITLE
want to deploy a simple and private elastic.

### ISSUE THREAD

**Issue by RupakRath** [oracle-quickstart/oci-elastic#23]
i am new to terraform so can any one help me how to do this, I need help like what to change and where to change to create a private and simple elastic

**Comment by lfeldman** [comment]
@RupakRath, could you please explain what you expect to obtain in detail? As I understand, you would like to disconnect VM from the public Internet and replace Internet GW with NAT GW? How this private cloud infra you would like to access - with DRG and VPN tunnel or FastConnect? BTW. This repository plays the role of illustration and just for testing purposes.

**Comment by lfeldman** [comment]
There is no response from the customer. Closing the ticket.

**Comment by RupakRath** [comment]
Only for internal use.

But company demand is to create this ELK in private subnet , without any
public ip

**Comment by lfeldman** [comment]
@RupakRath You can download the code and customize Terraform code according to customer demands. The purpose of this repo is to inspire Terraform developers for their own customized work.

**Comment by RupakRath** [comment]
Actually I am new to oci and terraform world.

I used that script, created ELK through resource  manager but it's creating
a public one.

Our requirement is to create a single stand alone elk but it should be a
private instance and also in private subnet.

So if possible requesting you to help me regarding this.
